name: "GitHub Actions"
author: "Calibre"
description: "Effortlessly add Calibre to your GitHub workflows"

runs:
  using: "docker"
  image: "docker://ghcr.io/calibreapp/github-actions/github-actions:main" 

inputs:
  command:
    description: The Calibre CLI command to run
    required: true

branding:
  icon: "code"
  color: "green"
